# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsquare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='difficulty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='knexmigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='knexmigrationslock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
    ]
