# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsquare', '0002_auto_20180903_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='color',
            new_name='difficulty',
        ),
        migrations.AlterField(
            model_name='game',
            name='bgg_average_rating',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='bgg_average_weight',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
